name: PAG
version: "0.2.0"
license: "GPL-2.0-or-later"
date: 2023-03-27
description: |
    Prescribed Automorphism Groups

authors:
    - name: Vedran Krcadinac
      url: https://web.math.pmf.unizg.hr/~krcko/homepage.html

maintainers:
    - name: Vedran Krcadinac
      url: https://web.math.pmf.unizg.hr/~krcko/homepage.html

GAP: "4.11"

needed-pkgs:
    - name: "GAPDoc"
      version: "1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "images"
      version: "1.3"
      url: "https://gap-packages.github.io/images/"
    - name: "GRAPE"
      version: "4.8"
      url: "https://gap-packages.github.io/grape"
    - name: "DESIGN"
      version: "1.7"
      url: "https://gap-packages.github.io/design"

suggested-pkgs:
    - name: "AssociationSchemes"
      version: "2.0"
      url: "http://www.jesselansdown.com/AssociationSchemes"
    - name: "GUAVA"
      version: "3.15"
      url: "https://gap-packages.github.io/guava"
    - name: "DifSets"
      version: "2.3.1"
      url: "https://dylanpeifer.github.io/difsets"

www: https://vkrcadinac.github.io/pag
readme: README.txt
packageinfo: https://vkrcadinac.github.io/pag/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/vkrcadinac/pag/releases/download/v0.2.0/PAG-0.2.0.tar.gz

abstract: |
    The <span class="pkgname">PAG</span> package contains functions for    constructing combinatorial objects with prescribed automorphism groups.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    automorphism group, block design, latin square, hadamard matrix.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Krc23</span>]   <b class='BibAuthor'>Krcadinac, V.</b>,
     <i class='BibTitle'>PAG, Prescribed Automorphism Groups,
             Version 0.2.0</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://vkrcadinac.github.io/pag">https://vkrcadinac.github.io/pag</a></span>.
    </p>
    

bibtex: |
    @misc{ PAG0.2.0,
      author =           {Krcadinac, V.},
      title =            {{PAG},   Prescribed  Automorphism  Groups,  {V}ersion
                          0.2.0},
      month =            {Mar},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href              {https://vkrcadinac.github.io/pag}
                          {\texttt{https://vkrcadinac.github.io/}\discretionary
                          {}{}{}\texttt{pag}}},
      keywords =         {automorphism   group;  block  design;  latin  square;
                          hadamard matrix},
      printedkey =       {Krc23}
    }

